apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset28
  namespace: wave2
spec:
  replicas: 8
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: ejercicio7
        image: busybox
